# The URL the site will be built for
base_url = "https://balliegojr.github.io"
title = "balliegojr"
taxonomies = [
    {name = "tags", feed=true},
]

generate_feed = true
feed_filename = "rss.xml"
ignored_content = ["**/code/**"]

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
show_reading_time = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "terminimal"
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"
smart_punctuation = true

[extra]
# Put all your custom variables here
author = "Ilson Balliego"
logo_text = "balliegojr"
page_titles = "combined"
accent_color = "green"
background_color = "dark"


menu_items = [
    {name = "blog", url = "$BASE_URL"},
    {name = "tags", url = "$BASE_URL/tags"},
    # {name = "archive", url = "$BASE_URL/archive"},
    {name = "about me", url = "$BASE_URL/about"},
    {name = "source", url = "https://github.com/balliegojr/blog", newtab = true},
]

enable_post_view_navigation = true
show_reading_time = true
